site_name: JOSSeph
site_description: OSS Metrics Extraction Pipeline
site_url: https://chesnokoff.github.io/oss-metrics/

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Config: config.md
  - Examples: examples.md
  - Output: output.md
  - FAQ: faq.md
