site_name: JOSSeph
site_description: OSS Metrics Extraction Pipeline
site_url: https://chesnokoff.github.io/oss-metrics/

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Config: config.md
  - Examples: examples.md
  - Output: output.md
  - FAQ: faq.md
  - Concepts:
      - How it works: concepts/how-it-works.md
  - Reference:
      - Config details: reference/config.md
      - IO details: reference/io.md
      - Pipeline: reference/pipeline.md
      - Extractors: reference/extractors.md
      - Errors: reference/errors.md
      - Architecture: reference/architecture.md
